temp - linux only

diff --git a/.github/workflows/prebuild.yaml b/.github/workflows/prebuild.yaml
--- a/.github/workflows/prebuild.yaml
+++ b/.github/workflows/prebuild.yaml
@@ -51,7 +51,7 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: ${{ env.GITHUB_SHA }}
-          path: prebuild
+          path: prebuild-branch
 
       - uses: actions/setup-node@v1
         with:
@@ -59,7 +59,9 @@ jobs:
 
       - name: Build
         run: |
-          cp -rf ../prebuild .
+          ls
+          mkdir prebuild
+          cp -rfv ./prebuild-branch/prebuild/* ./prebuild/
           npm install -g node-gyp@6.1
           npm install --ignore-scripts
           . prebuild/Linux/preinstall.sh
@@ -111,170 +113,170 @@ jobs:
               data: fs.readFileSync(assetName)
             });
 
-  macOS:
-    strategy:
-      matrix:
-        node: [15]
-        canvas_tag: ["v2.6.1"] # e.g. "v2.6.1"
-    name: ${{ matrix.canvas_tag}}, Node.js ${{ matrix.node }}, macOS
-    runs-on: macos-latest
-    env:
-      CANVAS_VERSION_TO_BUILD: ${{ matrix.canvas_tag }}
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          # ref: ${{ matrix.canvas_tag }}
-          fetch-depth: 0
+  # macOS:
+  #   strategy:
+  #     matrix:
+  #       node: [15]
+  #       canvas_tag: ["v2.6.1"] # e.g. "v2.6.1"
+  #   name: ${{ matrix.canvas_tag}}, Node.js ${{ matrix.node }}, macOS
+  #   runs-on: macos-latest
+  #   env:
+  #     CANVAS_VERSION_TO_BUILD: ${{ matrix.canvas_tag }}
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         # ref: ${{ matrix.canvas_tag }}
+  #         fetch-depth: 0
 
-      - uses: actions/setup-node@v1
-        with:
-          node-version: ${{ matrix.node }}
+  #     - uses: actions/setup-node@v1
+  #       with:
+  #         node-version: ${{ matrix.node }}
 
-      - name: Build
-        run: |
-          git checkout ${{ matrix.canvas_tag }}
-          git checkout $GITHUB_SHA -- prebuild/
-          npm install -g node-gyp@6.1
-          npm install --ignore-scripts
-          . prebuild/macOS/preinstall.sh
-          cp prebuild/macOS/binding.gyp binding.gyp
-          node-gyp rebuild -j 2
-          . prebuild/macOS/bundle.sh
+  #     - name: Build
+  #       run: |
+  #         git checkout ${{ matrix.canvas_tag }}
+  #         git checkout $GITHUB_SHA -- prebuild/
+  #         npm install -g node-gyp@6.1
+  #         npm install --ignore-scripts
+  #         . prebuild/macOS/preinstall.sh
+  #         cp prebuild/macOS/binding.gyp binding.gyp
+  #         node-gyp rebuild -j 2
+  #         . prebuild/macOS/bundle.sh
 
-      - name: Test binary
-        run: |
-          brew uninstall --force --ignore-dependencies cairo pango librsvg giflib harfbuzz
-          npm test
+  #     - name: Test binary
+  #       run: |
+  #         brew uninstall --force --ignore-dependencies cairo pango librsvg giflib harfbuzz
+  #         npm test
 
-      - name: Make bundle
-        id: make_bundle
-        run: . prebuild/tarball.sh
+  #     - name: Make bundle
+  #       id: make_bundle
+  #       run: . prebuild/tarball.sh
 
-      - name: Upload
-        uses: actions/github-script@v2
-        with:
-          script: |
-            const fs = require("fs");
-            const assetName = "${{ steps.make_bundle.outputs.asset_name }}";
-            const tagName = process.env.UPLOAD_TO || process.env.CANVAS_VERSION_TO_BUILD;
-            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
+  #     - name: Upload
+  #       uses: actions/github-script@v2
+  #       with:
+  #         script: |
+  #           const fs = require("fs");
+  #           const assetName = "${{ steps.make_bundle.outputs.asset_name }}";
+  #           const tagName = process.env.UPLOAD_TO || process.env.CANVAS_VERSION_TO_BUILD;
+  #           const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
 
-            const releases = await github.repos.listReleases({owner, repo});
-            const release = releases.data.find(r => r.tag_name === tagName);
-            if (!release)
-              throw new Error(`Tag ${tagName} not found. Did you make the GitHub release?`);
+  #           const releases = await github.repos.listReleases({owner, repo});
+  #           const release = releases.data.find(r => r.tag_name === tagName);
+  #           if (!release)
+  #             throw new Error(`Tag ${tagName} not found. Did you make the GitHub release?`);
 
-            const oldAsset = release.assets.find(a => a.name === assetName);
-            if (oldAsset)
-              await github.repos.deleteReleaseAsset({owner, repo, asset_id: oldAsset.id});
+  #           const oldAsset = release.assets.find(a => a.name === assetName);
+  #           if (oldAsset)
+  #             await github.repos.deleteReleaseAsset({owner, repo, asset_id: oldAsset.id});
 
-            // (This is equivalent to actions/upload-release-asset. We're
-            // already in a script, so might as well do it here.)
-            const r = await github.repos.uploadReleaseAsset({
-              url: release.upload_url,
-              headers: {
-                "content-type": "application/x-gzip",
-                "content-length": `${fs.statSync(assetName).size}`
-              },
-              name: assetName,
-              data: fs.readFileSync(assetName)
-            });
+  #           // (This is equivalent to actions/upload-release-asset. We're
+  #           // already in a script, so might as well do it here.)
+  #           const r = await github.repos.uploadReleaseAsset({
+  #             url: release.upload_url,
+  #             headers: {
+  #               "content-type": "application/x-gzip",
+  #               "content-length": `${fs.statSync(assetName).size}`
+  #             },
+  #             name: assetName,
+  #             data: fs.readFileSync(assetName)
+  #           });
 
-  Win:
-    strategy:
-      matrix:
-        node: [15]
-        canvas_tag: ["v2.6.1"] # e.g. "v2.6.1"
-    name: ${{ matrix.canvas_tag}}, Node.js ${{ matrix.node }}, Windows
-    runs-on: windows-latest
-    env:
-      CANVAS_VERSION_TO_BUILD: ${{ matrix.canvas_tag }}
-    steps:
-      # GitHub runners now have msys2 installed, but msys is not on the path and
-      # is apparently slow to start.
-      # https://github.com/msys2/setup-msys2#setup-msys2
-      # https://github.com/actions/virtual-environments/pull/632
-      - uses: msys2/setup-msys2@v2
-        with:
-          update: true
-          path-type: inherit
+  # Win:
+  #   strategy:
+  #     matrix:
+  #       node: [15]
+  #       canvas_tag: ["v2.6.1"] # e.g. "v2.6.1"
+  #   name: ${{ matrix.canvas_tag}}, Node.js ${{ matrix.node }}, Windows
+  #   runs-on: windows-latest
+  #   env:
+  #     CANVAS_VERSION_TO_BUILD: ${{ matrix.canvas_tag }}
+  #   steps:
+  #     # GitHub runners now have msys2 installed, but msys is not on the path and
+  #     # is apparently slow to start.
+  #     # https://github.com/msys2/setup-msys2#setup-msys2
+  #     # https://github.com/actions/virtual-environments/pull/632
+  #     - uses: msys2/setup-msys2@v2
+  #       with:
+  #         update: true
+  #         path-type: inherit
 
-      - uses: actions/setup-node@v1
-        with:
-          node-version: ${{ matrix.node }}
+  #     - uses: actions/setup-node@v1
+  #       with:
+  #         node-version: ${{ matrix.node }}
 
-      - uses: actions/checkout@v2
-        with:
-          # ref: ${{ matrix.canvas_tag }}
-          fetch-depth: 0 # temp
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         # ref: ${{ matrix.canvas_tag }}
+  #         fetch-depth: 0 # temp
 
-      - name: Build
-        run: |
-          git checkout ${{ matrix.canvas_tag }}
-          git checkout $env:GITHUB_SHA -- prebuild/
-          npm install -g node-gyp@6.1
-          npm install --ignore-scripts
-          msys2 -c ". prebuild/Windows/preinstall.sh"
-          msys2 -c "cp prebuild/Windows/binding.gyp binding.gyp"
-          msys2 -c "node-gyp rebuild -j 2"
+  #     - name: Build
+  #       run: |
+  #         git checkout ${{ matrix.canvas_tag }}
+  #         git checkout $env:GITHUB_SHA -- prebuild/
+  #         npm install -g node-gyp@6.1
+  #         npm install --ignore-scripts
+  #         msys2 -c ". prebuild/Windows/preinstall.sh"
+  #         msys2 -c "cp prebuild/Windows/binding.gyp binding.gyp"
+  #         msys2 -c "node-gyp rebuild -j 2"
 
-      - name: Install Depends
-        run: |
-          Invoke-WebRequest "http://www.dependencywalker.com/depends22_x64.zip" -OutFile depends22_x64.zip
-          7z e depends22_x64.zip
-      - name: Bundle pt 2
-        shell: msys2 {0}
-        run: |
-          ./depends.exe -c -oc depends.csv build\\Release\\canvas.node || true
-          [ -f depends.csv ] || { echo "error invoking depends.exe"; exit 1; }
+  #     - name: Install Depends
+  #       run: |
+  #         Invoke-WebRequest "http://www.dependencywalker.com/depends22_x64.zip" -OutFile depends22_x64.zip
+  #         7z e depends22_x64.zip
+  #     - name: Bundle pt 2
+  #       shell: msys2 {0}
+  #       run: |
+  #         ./depends.exe -c -oc depends.csv build\\Release\\canvas.node || true
+  #         [ -f depends.csv ] || { echo "error invoking depends.exe"; exit 1; }
 
-          copies=$(comm -12 \
-            <(cat depends.csv | cut -d ',' -f2 | sed 's/"//g' | tr '[:upper:]' '[:lower:]' | sort) \
-            <(find /mingw64/bin -name '*.dll' -printf "%f\n" | tr '[:upper:]' '[:lower:]' | sort) \
-          );
+  #         copies=$(comm -12 \
+  #           <(cat depends.csv | cut -d ',' -f2 | sed 's/"//g' | tr '[:upper:]' '[:lower:]' | sort) \
+  #           <(find /mingw64/bin -name '*.dll' -printf "%f\n" | tr '[:upper:]' '[:lower:]' | sort) \
+  #         );
 
-          echo "Copies:"
-          echo $copies
+  #         echo "Copies:"
+  #         echo $copies
 
-          for dll in $copies; do
-            cp /mingw64/bin/$dll build/Release
-          done;
+  #         for dll in $copies; do
+  #           cp /mingw64/bin/$dll build/Release
+  #         done;
 
-      - name: Test binary
-        # By not running in msys2, this doesn't have access to the msys2 libs
-        run: npm test
+  #     - name: Test binary
+  #       # By not running in msys2, this doesn't have access to the msys2 libs
+  #       run: npm test
 
-      - name: Make asset
-        id: make_bundle
-        # I can't figure out why this isn't an env var already. It shows up with `env`.
-        run: msys2 -c "UPLOAD_TO=${{ env.UPLOAD_TO }} CANVAS_VERSION_TO_BUILD=${{ env.CANVAS_VERSION_TO_BUILD}} . prebuild/tarball.sh"
+  #     - name: Make asset
+  #       id: make_bundle
+  #       # I can't figure out why this isn't an env var already. It shows up with `env`.
+  #       run: msys2 -c "UPLOAD_TO=${{ env.UPLOAD_TO }} CANVAS_VERSION_TO_BUILD=${{ env.CANVAS_VERSION_TO_BUILD}} . prebuild/tarball.sh"
 
-      - name: Upload
-        uses: actions/github-script@v2
-        with:
-          script: |
-            const fs = require("fs");
-            const assetName = "${{ steps.make_bundle.outputs.asset_name }}";
-            const tagName = process.env.UPLOAD_TO || process.env.CANVAS_VERSION_TO_BUILD;
-            const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
+  #     - name: Upload
+  #       uses: actions/github-script@v2
+  #       with:
+  #         script: |
+  #           const fs = require("fs");
+  #           const assetName = "${{ steps.make_bundle.outputs.asset_name }}";
+  #           const tagName = process.env.UPLOAD_TO || process.env.CANVAS_VERSION_TO_BUILD;
+  #           const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
 
-            const releases = await github.repos.listReleases({owner, repo});
-            const release = releases.data.find(r => r.tag_name === tagName);
-            if (!release)
-              throw new Error(`Tag ${tagName} not found. Did you make the GitHub release?`);
+  #           const releases = await github.repos.listReleases({owner, repo});
+  #           const release = releases.data.find(r => r.tag_name === tagName);
+  #           if (!release)
+  #             throw new Error(`Tag ${tagName} not found. Did you make the GitHub release?`);
 
-            const oldAsset = release.assets.find(a => a.name === assetName);
-            if (oldAsset)
-              await github.repos.deleteReleaseAsset({owner, repo, asset_id: oldAsset.id});
+  #           const oldAsset = release.assets.find(a => a.name === assetName);
+  #           if (oldAsset)
+  #             await github.repos.deleteReleaseAsset({owner, repo, asset_id: oldAsset.id});
 
-            // (This is equivalent to actions/upload-release-asset. We're
-            // already in a script, so might as well do it here.)
-            const r = await github.repos.uploadReleaseAsset({
-              url: release.upload_url,
-              headers: {
-                "content-type": "application/x-gzip",
-                "content-length": `${fs.statSync(assetName).size}`
-              },
-              name: assetName,
-              data: fs.readFileSync(assetName)
-            });
+  #           // (This is equivalent to actions/upload-release-asset. We're
+  #           // already in a script, so might as well do it here.)
+  #           const r = await github.repos.uploadReleaseAsset({
+  #             url: release.upload_url,
+  #             headers: {
+  #               "content-type": "application/x-gzip",
+  #               "content-length": `${fs.statSync(assetName).size}`
+  #             },
+  #             name: assetName,
+  #             data: fs.readFileSync(assetName)
+  #           });
